### ISSUE TITLE
Update Storage URL's

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-tools#9]
We are now retrieving images from : 
- https://s1-amz-par.imagify.io
- https://s2-amz-par.imagify.io
And not only from https://storage.imagify.io, the test should be updated

**Comment by Screenfeed** [comment]
You mean we're using the 3 URLs?

**Comment by jbma** [comment]
Right now we use : 
https://s1-amz-par.imagify.io
https://s2-amz-par.imagify.io
But we can fallback if some services are down to storage.imagify.io

**Comment by Screenfeed** [comment]
OK, thanks for the intel.

**Comment by jbma** [comment]
You're welcome

![intel](https://user-images.githubusercontent.com/2565525/39045436-39e76616-4493-11e8-966a-1dc2d77ace7b.jpg)

**Comment by Screenfeed** [comment]
@jbma Do we have a static file I can request?
For example for `storage.imagify.io` I use `http://storage.imagify.io/images/index.png`.

**Comment by Shakup** [comment]
@jbma @Screenfeed 

Here a static file to request:
http://s2-amz-par.imagify.io/wpm.png

**Comment by Screenfeed** [comment]
OK, perfect for s2 👍 
And now the same for s1 pleaz? ❤️

**Comment by Shakup** [comment]
@Screenfeed its complicated because the s1 have a TTL on all images

**Comment by Screenfeed** [comment]
@Shakup What about html, css, js, php, txt, md...?
